platform :ios, '9.0'




target 'NSApplication2.2' do

  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Alamofire', '~> 4.7'
pod 'Kingfisher', '~> 4.0'
pod 'SwiftIcons', '~> 2.0.1'
pod 'SVProgressHUD'
pod 'Cosmos', '~> 16.0'
pod "AssistantKit"
pod 'SwiftEventBus', :tag => '2.2.0', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
pod 'SwiftyJSON', '~> 4.0'
pod 'BadgeSwift', '~> 5.0'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod "MXParallaxHeader"
pod "Atributika"
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'ImageSlideshow', '~> 1.6'
pod "ImageSlideshow/Kingfisher"
pod 'Google-Mobile-Ads-SDK'
pod 'RealmSwift'
pod 'SwiftWebVC'
pod 'Fabric', '~> 1.9.0'
pod 'Crashlytics', '~> 3.12.0'
pod "SkeletonView"
pod 'libPhoneNumber-iOS', '~> 0.8'



post_install do |installer|
	
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end

    installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            end
         end
     end

     installer.pods_project.targets.each do |target|

	 target.build_configurations.each do |config|
             config.build_settings['SWIFT_VERSION'] = '4.0'
         end

       	if target.name == 'StepIndicator'
            target.build_configurations.each do |config|
               config.build_settings['SWIFT_VERSION'] = '5.0'
             end
        end

	if target.name == 'SkeletonView'
            target.build_configurations.each do |config|
               config.build_settings['SWIFT_VERSION'] = '5.0'
             end
        end

      end

end



end
